application:
  title: Validação de senha
  description: |
    Esta API é responsável pela validação dos critérios de aceite para que uma string de senha seja válida
      - Nove ou mais caracteres
      - Ao menos 1 dígito
      - Ao menos 1 letra mínuscula
      - Ao menos 1 letra maíscula
      - Ao menos 1 caractere especial
        - Considere como especial os seguintes caracteres: !@#$%^&*()-+
      - Não possuir caracteres repetidos dentro do conjunto
      - Espaços em branco não devem ser considerados como caracteres válidos

validate:
  password:
    minimum:
      length: 9
    characterSpecial: '!@#$%^&*()-+'

server:
  port: 8081
  servlet:
    context-path: /iti

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method

